import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load Stardom font
const stardom = localFont({
  src: [
    {
      path: '../fonts/Stardom_Complete/Fonts/WEB/fonts/Stardom-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-stardom',
  display: 'swap',
});

// Load General Sans font with multiple weights
const generalSans = localFont({
  src: [
    {
      path: '../fonts/GeneralSans_Complete/Fonts/WEB/fonts/GeneralSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/GeneralSans_Complete/Fonts/WEB/fonts/GeneralSans-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/GeneralSans_Complete/Fonts/WEB/fonts/GeneralSans-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/GeneralSans_Complete/Fonts/WEB/fonts/GeneralSans-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-general-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${stardom.variable} ${generalSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
